# This is a basic workflow to help you get started with Actions

# name: Push Docker GCR and release
name: Release a new version on github

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm install yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
        # - run: yarn test
        env:
          CI: true
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PUBLIC_ADMIN_URL: ${{ secrets.PUBLIC_ADMIN_URL }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          # LOGZIO_TOKEN: ${{ secrets.LOGZIO_TOKEN }}
          CDN_BASE_URL: ${{ secrets.CDN_BASE_URL }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          APP_KEYS: ${{ secrets.APP_KEYS }}
  Release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # # # This workflow contains a single job called "GCR"
  # GCR:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Push to Google Container Registry
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: _json_key
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         registry: asia.gcr.io
  #         repository: ecf-test/nda-back
  #         tags: latest
  #         dockerfile: Dockerfile
  GCR:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.6.0
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: teak-component-346005
          image_name: nda-back
          image_tag: latest
          build_args: CDN_BASE_URL=${{ secrets.CDN_BASE_URL }},AWS_ACCESS_SECRET=${{ secrets.AWS_ACCESS_SECRET }},AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }},AWS_BUCKET=${{ secrets.AWS_BUCKET }},APP_KEYS=${{ secrets.APP_KEYS }}
