# This is a basic workflow to help you get started with Actions

# name: Push Docker GCR and release
name: Release a new version on github

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: npm install yarn
      - run: yarn install --frozen-lockfile
      - run: echo "$DATABASE_URL"
      - run: yarn build
        # - run: yarn test
        env:
          CI: true
  Release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  # # This workflow contains a single job called "GCR"
  # GCR:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Google Container Registry
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: _json_key
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         registry: asia.gcr.io
  #         repository: ecf-test/ecf-back
  #         tags: latest
  #         dockerfile: Dockerfile
